spring:
  application:
    name: hello-consumer-feign-hystrix
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

## 开启hystrix
feign:
  hystrix:
    enabled: true

## hystrix熔断触发默认超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:
              2000

# 启用 HystrixDashboard
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
