server:
  port: 8083

spring:
  application:
    name: hello-consumer-ribbon
  # 开启失败重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

restTemplate:
  ribbon:
    MaxAutoRetries: 3
    # Interval to refresh the server list from the source
    ServerListRefreshInterval: 2000
    ConnectTimeout: 3000
    ReadTimeout: 3000


eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
    register-with-eureka: true

