server:
  port: 8762

spring:
  application:
    name: eureka-server
  profiles: p2
## eureka配置
eureka:
  instance:
    ## 注册服务器的名称
    hostname: 127.0.0.1:8762
  client:
    ## 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    ## 是否从eureka服务器获取注册信息，所以这里是false
    register-with-eureka: true
    ## 是否注册自身到eureka服务器,因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/

